### ISSUE TITLE
Race condition: data race

### ISSUE THREAD

**Issue by fe1t** [ClockworkSoul/smudge#28] opened 2018-04-29 22:40 UTC
Hi again,

I was building my project with flag -race as someone suggested me.
Suddenly, I found that this warning occurred: [https://pastebin.com/Nz7idxhZ](Pastebin)

I barely use smudge, not even broadcasting, which you can see from my code: [https://github.com/fe1t/blockchain_programming_in_golang/tree/fix_race](Github)

Most of the code are in server.go:ConfigServer func(), some other is only in cli.go for customizing logger.

I'm not sure if this will cause the problem.

If you could help me check this, I'll be appreciate and thankful.

**Comment by fe1t** [comment] 2018-04-29 22:55
For more warning, https://pastebin.com/qZSrYc0k.

**Comment by eelcocramer** [comment] 2018-04-30 13:12
I wonder if these DATA RACE warnings are actually a problem or just, like notified, warnings.

I looked around a bit and more warnings can be resolved by locking access to variables but it is quite some work to get this right. Would it solve actually errors doing this?

**Comment by eelcocramer** [comment] 2018-04-30 13:18
As an example [here](https://github.com/eelcocramer/smudge/commit/196d1e11690614eff5ecedb5b37c9416ceb43369) is a commit that enables save access to the `emitCounter`s but there are several more data race warnings beyond this change.

**Comment by clockworksoul** [comment] 2018-04-30 13:50
We can certainly do this, but these are primitive values that are only atomically incremented by design. They're designed to be modified by multiple threads.

As far as I can tell, everything that needs to be reads/write locked (the maps) is...

**Closed as completed** 2018-05-21 08:59 UTC
